Fix tina require
Without this, opening a browser window to a fresh pixelbox project shows
this error:

    Error: Cannot find module 'TINA' from '/mnt/futokoro/fiddle/ld39/node_modules'

Seems tina just need to be required lower case to fix it. -POLM